export const portofolio = [
  {
    title: 'Movie Watchlist App',
    date: '(Juni - Juli 2026)',
    desc: 'A full-stack movie watchlist application built with Next.js App Router, Express.js, Prisma ORM, and PostgreSQL. Users can securely manage personal watchlists and add own movie list through JWT authentication and a modern responsive interface.',
    img: 'img/portofolio/watchlistmovieapp.png',
    link: 'https://watchlistmovieapp.vercel.app/',
  },
  {
    title: 'AYANA Bali Clone Webpage',
    date: '(Feb - Juni 2026)',
    desc: 'A high-fidelity luxury hotel website clone inspired by AYANA Bali, built with Next.js and Tailwind CSS, focused on recreating responsive layouts, advanced scroll interactions, and premium visual presentation to emulate a modern hospitality web experience.',
    img: 'img/portofolio/ayana-clone.png',
    link: 'https://ayana-clone.vercel.app/',
  },
  {
    title: 'Dlooti Webpage',
    date: '(Juni 2025 - Juli 2025)',
    desc: 'Dlooti, a cake shop product catalog website based on Next.js and Firebase, makes it easy for users to browse products like soft cookies, brownies, and custom cakes, and leave reviews after logging in.',
    img: 'img/portofolio/dlooti.png',
    link: 'https://dlooti.vercel.app/',
  },
  {
    title: 'Dlooti Tracking Delivery',
    date: '(Agustus 2025 - September 2025)',
    desc: 'Next.js + Firebase app enabling real-time driver tracking, geocoded addresses, and delivery status management to give the information about delivery to the client.',
    img: 'img/portofolio/dlooti-tracking.png',
    link: 'https://dlooti-tracking-package.vercel.app/',
  },
  {
    title: 'Book Track Mobile App with ReactNative',
    date: '(Januari 2026)',
    desc: 'React Native (Expo) mobile app for managing personal book collections with user authentication, enabling registered users to log in, create and manage their own book collections.',
    img: 'img/portofolio/react-native-booktrack-project.jpeg',
    link: 'https://https://github.com/Rivensin/Book-Track-App-ReactNative',
  },
  {
    title: 'Product Management Web With Laravel & Nextjs',
    date: '(November 2025 - Desember 2025)',
    desc: 'The Product Management is a platform created by Laravel as backend and Nextjs as frontend with user authentication, enabling registered users to log in, create and manage their own product, and make receipt for the sales.',
    img: 'img/portofolio/laravel-nextjs.png',
    link: 'https://github.com/Rivensin/laravel-nextjs',
  },
  {
    title: 'Blog App with React.js',
    date: '(Februari 2025 - April 2025)',
    desc: 'The Blog App is a platform with user authentication, enabling registered users to log in, create and manage their own posts, and explore posts from other users.',
    img: 'img/portofolio/blog-app.png',
    link: 'https://rivensin.github.io/React-Blog-App/',
  },
  {
    title: 'Simple Amazon E-Commerce Web',
    date: '(Desember 2024)',
    desc: 'A simple copy Of Amazon E-commerce Website built with HTML,CSS,JavaScript to practice JavaScript feature.',
    img: 'img/portofolio/amazon.png',
    link: 'https://rivensin.github.io/amazon-copy.com/',
  },
  {
    title: 'Landing Page Youtube',
    date: '(Desember 2024)',
    desc: 'A simple landing page built with HTML & CSS to practice utility classes, layouts, and responsiveness.',
    img: 'img/portofolio/youtube-project.png',
    link: 'https://rivensin.github.io/Youtube-Home/',
  },
]